name: Build & Push CPU/GPU Dev/Prod Images

on:
  push:
    branches: [ main ]
    tags:    [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.expand.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Install deps for expand script
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-yaml

      - name: Expand matrix.yaml
        id: expand
        run: |
          matrix_json=$(./scripts/expand_matrix.py)
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

  build:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=py${{ matrix.python }}-${{ matrix.extra }}-${{ matrix.mode }}
            type=sha,format=short,prefix=sha-
            type=ref,event=tag

      - name: Build & Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          build-args: |
            BASE_IMAGE=${{ matrix.base }}
            PYTHON_VERSION=${{ matrix.python }}
            EXTRA=${{ matrix.extra }}
            MODE=${{ matrix.mode }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Attest Provenance
        if: success()
        uses: actions/attest-build-provenance@v1
        with:
          subject-name:   ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
